### ISSUE TITLE
Long Term Support Policy

### ISSUE THREAD

**Issue by corbinu** [prebuild/prebuild#161]
This is in response to:

https://github.com/mafintosh/prebuild-install/pull/27

I am definitely +1 on this. 

However I do think that a support policy should be set. 

I was thinking Maintenance and Current + 3 Months 

https://github.com/nodejs/LTS

So at the moment 0.X and 5 are out of support. Node 4 would end 2018-04-01 and Node 7 would end 3 months after Node 8 drops

**Comment by vweevers** [comment]
Though we don't have an official policy (in writing), this is already how it goes. We follow Node's LTS schedule and when a version reaches EOL we drop it - usually some time after (not because of policy, but because someone has to take the initiative and dropping a version isn't a priority). In addition, when we drop a version we always bump major. I don't think we need to officially extend support beyond EOL dates - those lifetimes are long enough IMO.
