### ISSUE TITLE
Work with namespaced packages

### ISSUE THREAD

**Issue by flotwig** [prebuild/prebuild#245]
It doesn't seem like `prebuild --upload-all` works with packages that have namespaced names (i.e., `@cypress/registry-js`. The problem occurs when uploading the built archives to GitHub:

```
prebuild info begin Prebuild version 8.2.0
prebuild info build Uploading 1 prebuilds(s) to Github releases
prebuild ERR! build Error: can only upload files
prebuild ERR! build     at fs.stat (C:\projects\registry-js\node_modules\ghreleases\ghreleases.js:65:23)
prebuild ERR! build     at FSReqWrap.oncomplete (fs.js:153:5)
```

It seems like `prebuild` is trying to upload the entire `prebuilds/@cypress` directory that is generated instead of the individual `.tar.gz` files within it.

**Comment by vweevers** [comment]
By "namespaced" do you mean the package is in a monorepo, or is it solely about an npm scope?

**Comment by flotwig** [comment]
Solely about npm scope

**Comment by vweevers** [comment]
> It seems like `prebuild` is trying to upload the entire `prebuilds/@cypress` directory that is generated instead of the individual `.tar.gz` files within it.

Perhaps we should flatten it beforehand, e.g. replace the slash in the `@cypress/registry-js` package name so that you end up with a flat `prebuilds/@cypress-registry-js-[..].tgz` structure. But I'm not sure how related tools (`prebuild-install`) deal with scoped names, if at all.

**Comment by vweevers** [comment]
Looking back, support for scoped names was partially fixed in https://github.com/prebuild/prebuild/pull/43. It works when doing an single upload, because in that case the tarpath is taken from the result of the `prebuild` function:

https://github.com/prebuild/prebuild/blob/b2a62f264d9ba35ef824caf1d29e758d52d6c7bf/bin.js#L56-L60

With `--upload-all` however, the directory structure is assumed to be one level deep:

https://github.com/prebuild/prebuild/blob/b2a62f264d9ba35ef824caf1d29e758d52d6c7bf/bin.js#L49-L52

So that would be the best place to fix it (keeping the directory structure as-is).
