### ISSUE TITLE
Ability to not support a platform nicely

### ISSUE THREAD

**Issue by No9** [prebuild/prebuild#42]
So hyper-level  doesn't support windows or illumOS right now due to this issue
https://github.com/Level/leveldown-hyper/issues/15 
Should prebuild support the generation of stub releases so when the user tries to install them they get a friendly response instead of build fail spew? 

The command would be something like

```
prebuild --notsupported win sunos -u <git-key>
```

This would generate a tar with a single file notsupported.txt in it.

When prebuild trys to install on the endusers machine it checks to see if the tar is just contains a file if so print a friendly message?

**Comment by ralphtheninja** [comment]
I like the idea. The tar only contains a single file right now so we would have to check the file name or something like that.

**Comment by brett19** [comment]
Having a not-supported file seems a bit strange, as that would mean GitHub releases section would show that there is a file for the unsupported platform, but then downloading it would yield only a random marker file.  Why not simply add a category to package.json that indicates platform support?  This aligns more closely with the fact that any particular version of the source-code might or might not support a particular platform, rather than it being dependant on the prebuilds themselves.

**Comment by ralphtheninja** [comment]
> Why not simply add a category to package.json that indicates platform support?

Very good point. It must be much better to know beforehand whether something supports platform X or not and just not try downloading in the first place. We stop earlier in the chain.

**Comment by ralphtheninja** [comment]
> Why not simply add a category to package.json that indicates platform support? This aligns more closely with the fact that any particular version of the source-code might or might not support a particular platform, rather than it being dependant on the prebuilds themselves.

@brett19 I think this is a pretty good feature. Feel like specing out what this could look like in `package.json`?

**Comment by brett19** [comment]
For sure.  Do you have any thoughts on what level of granularity we should have for this?  Additionally, I suspect we should write this as a 'is supported' rather than 'is not supported' kind of semantic.

**Comment by brett19** [comment]
Oops.  Someone already did this for us, see here:
https://docs.npmjs.com/files/package.json#os
https://docs.npmjs.com/files/package.json#cpu

**Comment by ralphtheninja** [comment]
> Oops. Someone already did this for us, see here:
> https://docs.npmjs.com/files/package.json#os
> https://docs.npmjs.com/files/package.json#cpu

Oh nice!

**Comment by ralphtheninja** [comment]
@brett19 What kind of effect does that have with npm? Is that only for being explicit of which systems it runs on or does npm actually take action as in failing the install?

**Comment by ralphtheninja** [comment]
Like, we would like to use those properties, if present, to not even try downloading something we know is not supported and give a more useful message, but we don't want npm to take any other action on our behalf.

**Comment by vweevers** [comment]
If the package is an optionalDependency, those properties will lead npm to show a warning, skip the package, but not fail. If the package is a normal dependency then npm will fail, at least in recent npm.

If you know for a fact that a certain platform doesn't work then you can blacklist it with `!`, rather than whitelisting supported platforms which has a downside: a platform not being officially supported (or the author not even knowing a particular platform exists) does not necessarily mean it won't work.

I think that covers it?
